/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Benjamin Bardou (https://sketchfab.com/meryon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/cesar-louvre-museum-30f43907f7814582b5dacbbadbabbe6d
title: César - Louvre Museum
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Cesar(props) {
  const { nodes, materials } = useGLTF('/cesar/cesar.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.05}>
        <group position={[-8.45, -6.98, -5.85]}>
          <mesh geometry={nodes.Object_3.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_4.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_5.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_8.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_10.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.lambert5SG} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.lambert5SG} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/cesar/cesar.gltf')
