/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Loïc Norgeot (https://sketchfab.com/norgeotloic)
license: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
source: https://sketchfab.com/3d-models/ship-in-a-bottle-9ddbc5b32da94bafbfdb56e1f6be9a38
title: Ship in a bottle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Scene(props) {
  const { nodes, materials } = useGLTF('/scene/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.04, -209.12, -130.62]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.plaque_export_plaqueexport_baked_material_0.geometry} material={materials.plaqueexport_baked_material} />
          </group>
          <group position={[0, -2.02, -61.7]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.support_export_supportexport_baked_material001_0.geometry} material={materials['supportexport_baked_material.001']} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.bottle_export001_bottle_inside_0.geometry} material={materials.bottle_inside} />
          </group>
          <group position={[-20.54, -129.33, 36.19]} rotation={[-Math.PI / 2, 0, 0]} scale={277.24}>
            <mesh geometry={nodes.sea_mer_0.geometry} material={materials.material} />
            <mesh geometry={nodes.sea_fond_0.geometry} material={materials.fond} />
          </group>
          <group position={[0, -188.18, 39.11]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100.32}>
            <mesh geometry={nodes.boat_export_veliero001_baked_material_0.geometry} material={materials.veliero001_baked_material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.cap_export_capexport_baked_material_0.geometry} material={materials.capexport_baked_material} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.bottle_export_bottleexport_baked_material_0.geometry} material={materials.bottleexport_baked_material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/scene/scene.gltf')
